version: '3.8'

services:
  t1test:
    container_name: t1test
    depends_on:
      task_db:
        condition: service_healthy
    ports:
      - "8080:8080"
    build:
      context: .
    environment:
      DB_USERNAME: rushglow
      DB_PASSWORD: password1
      DB_NAME: task_db
      DB_HOST: task_db
      DB_PORT: 5432
      APP_PORT: 8080
    networks:
      - app_network

  task_db:
    container_name: task_db
    image: 'postgres:16.0'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=rushglow
      - POSTGRES_PASSWORD=password1
      - POSTGRES_DB=task_db
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d task_db -U rushglow"]
      interval: 10s
      retries: 5
      start_period: 5s

networks:
  app_network:
    driver: bridge