spring:
  application:
    name: t1Test

  mail:
    host: smtp.gmail.com
    port: 587
    username: asasian71@gmail.com
    password: lbkb ckww qvio hpjj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.xml

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
      show-sql: true
    properties:
      hibernate:
        format_sql: true

t1:
  scan-path: org.batukhtin.t1test
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:broker_t1:29092}
    consumer:
      group-id: t1-demo
      servers: ${KAFKA_CONSUMER_SERVERS:broker_t1:29092}
      max-poll-records: 10
      session-timeout: 10000
      max-poll-interval-ms: 300000
      client-topic: task-status-updates
    producer:
      enable: true
    topic:
      email_send: t1_demo_email_send
    listener:
      poll-timeout: 1000

server:
  port: ${APP_PORT}
