create table users
(
    id       bigint generated by default as identity
        primary key,
    password varchar(255),
    role     varchar(255),
    mail varchar(255) unique,
    username varchar(255)
        constraint ukr43af9ap4edm43mmtq01oddj6
            unique
);

create table tasks
(
    id           bigint generated by default as identity
        primary key,
    description  varchar(4096) not null,
    title        varchar(255)  not null,
    status varchar(50) not null default 'NEW'
);

create table user_tasks
(
    user_id bigint
        constraint fksrpyfa9asu2ymkcqr7jol85o2
            references users,
    task_id bigint not null
        primary key
        constraint fkqgw406rca7wgi6lsvcli7vltl
            references tasks
);

INSERT INTO users (password, role, mail, username)
VALUES ('$2a$12$I3vccD2NqyJb2Uqvb6zBKuMJ0pD6dezJGzukd8xn65IRFxU/sMhee','ROLE_USER','lskorpl@mail.ru','user')